package jp.co.softwiz.main.domain;

import java.util.Date;

public class TAreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.areano
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Integer areano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.areadiv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String areadiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String usediv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.areaname
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.etc
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String etc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.areano
     *
     * @return the value of t_area_info.areano
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Integer getAreano() {
        return areano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.areano
     *
     * @param areano the value for t_area_info.areano
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setAreano(Integer areano) {
        this.areano = areano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.areadiv
     *
     * @return the value of t_area_info.areadiv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getAreadiv() {
        return areadiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.areadiv
     *
     * @param areadiv the value for t_area_info.areadiv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setAreadiv(String areadiv) {
        this.areadiv = areadiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.usediv
     *
     * @return the value of t_area_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getUsediv() {
        return usediv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.usediv
     *
     * @param usediv the value for t_area_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setUsediv(String usediv) {
        this.usediv = usediv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.areaname
     *
     * @return the value of t_area_info.areaname
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.areaname
     *
     * @param areaname the value for t_area_info.areaname
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.etc
     *
     * @return the value of t_area_info.etc
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getEtc() {
        return etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.etc
     *
     * @param etc the value for t_area_info.etc
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setEtc(String etc) {
        this.etc = etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.createdate
     *
     * @return the value of t_area_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.createdate
     *
     * @param createdate the value for t_area_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.createuser
     *
     * @return the value of t_area_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.createuser
     *
     * @param createuser the value for t_area_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.modifydate
     *
     * @return the value of t_area_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.modifydate
     *
     * @param modifydate the value for t_area_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.modifyuser
     *
     * @return the value of t_area_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.modifyuser
     *
     * @param modifyuser the value for t_area_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.deleteflag
     *
     * @return the value of t_area_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.deleteflag
     *
     * @param deleteflag the value for t_area_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.deletedate
     *
     * @return the value of t_area_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.deletedate
     *
     * @param deletedate the value for t_area_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area_info.deleteuser
     *
     * @return the value of t_area_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area_info.deleteuser
     *
     * @param deleteuser the value for t_area_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}