package jp.co.softwiz.main.domain;

public class TBoardMasterInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_board_master_info.boardid
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	private String boardid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_board_master_info.boardname
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	private String boardname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_board_master_info.boardtype
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	private String boardtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_board_master_info.usediv
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	private String usediv;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_board_master_info.boardid
	 * @return  the value of t_board_master_info.boardid
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public String getBoardid() {
		return boardid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_board_master_info.boardid
	 * @param boardid  the value for t_board_master_info.boardid
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public void setBoardid(String boardid) {
		this.boardid = boardid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_board_master_info.boardname
	 * @return  the value of t_board_master_info.boardname
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public String getBoardname() {
		return boardname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_board_master_info.boardname
	 * @param boardname  the value for t_board_master_info.boardname
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public void setBoardname(String boardname) {
		this.boardname = boardname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_board_master_info.boardtype
	 * @return  the value of t_board_master_info.boardtype
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public String getBoardtype() {
		return boardtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_board_master_info.boardtype
	 * @param boardtype  the value for t_board_master_info.boardtype
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public void setBoardtype(String boardtype) {
		this.boardtype = boardtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_board_master_info.usediv
	 * @return  the value of t_board_master_info.usediv
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public String getUsediv() {
		return usediv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_board_master_info.usediv
	 * @param usediv  the value for t_board_master_info.usediv
	 * @mbggenerated  Fri Apr 25 10:48:29 JST 2014
	 */
	public void setUsediv(String usediv) {
		this.usediv = usediv;
	}
}