package jp.co.softwiz.main.domain;

public class TBoardMasterInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_master_info.boardid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String boardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_master_info.boardname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String boardname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_master_info.boardid
     *
     * @return the value of t_board_master_info.boardid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getBoardid() {
        return boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_master_info.boardid
     *
     * @param boardid the value for t_board_master_info.boardid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setBoardid(String boardid) {
        this.boardid = boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_master_info.boardname
     *
     * @return the value of t_board_master_info.boardname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getBoardname() {
        return boardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_master_info.boardname
     *
     * @param boardname the value for t_board_master_info.boardname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setBoardname(String boardname) {
        this.boardname = boardname;
    }
}