package jp.co.softwiz.main.domain;

import java.util.Date;

public class TBoardFileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.fileno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Long fileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.boardno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Long boardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.originfilename
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String originfilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.savefilename
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String savefilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.filesize
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Long filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.mimetype
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String mimetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.filepath
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String usediv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_board_file_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.fileno
     *
     * @return the value of t_board_file_info.fileno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Long getFileno() {
        return fileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.fileno
     *
     * @param fileno the value for t_board_file_info.fileno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setFileno(Long fileno) {
        this.fileno = fileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.boardno
     *
     * @return the value of t_board_file_info.boardno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Long getBoardno() {
        return boardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.boardno
     *
     * @param boardno the value for t_board_file_info.boardno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setBoardno(Long boardno) {
        this.boardno = boardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.originfilename
     *
     * @return the value of t_board_file_info.originfilename
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getOriginfilename() {
        return originfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.originfilename
     *
     * @param originfilename the value for t_board_file_info.originfilename
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setOriginfilename(String originfilename) {
        this.originfilename = originfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.savefilename
     *
     * @return the value of t_board_file_info.savefilename
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getSavefilename() {
        return savefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.savefilename
     *
     * @param savefilename the value for t_board_file_info.savefilename
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setSavefilename(String savefilename) {
        this.savefilename = savefilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.filesize
     *
     * @return the value of t_board_file_info.filesize
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Long getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.filesize
     *
     * @param filesize the value for t_board_file_info.filesize
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setFilesize(Long filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.mimetype
     *
     * @return the value of t_board_file_info.mimetype
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getMimetype() {
        return mimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.mimetype
     *
     * @param mimetype the value for t_board_file_info.mimetype
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.filepath
     *
     * @return the value of t_board_file_info.filepath
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.filepath
     *
     * @param filepath the value for t_board_file_info.filepath
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.usediv
     *
     * @return the value of t_board_file_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getUsediv() {
        return usediv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.usediv
     *
     * @param usediv the value for t_board_file_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setUsediv(String usediv) {
        this.usediv = usediv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.createdate
     *
     * @return the value of t_board_file_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.createdate
     *
     * @param createdate the value for t_board_file_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.createuser
     *
     * @return the value of t_board_file_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.createuser
     *
     * @param createuser the value for t_board_file_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.modifydate
     *
     * @return the value of t_board_file_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.modifydate
     *
     * @param modifydate the value for t_board_file_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.modifyuser
     *
     * @return the value of t_board_file_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.modifyuser
     *
     * @param modifyuser the value for t_board_file_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.deleteflag
     *
     * @return the value of t_board_file_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.deleteflag
     *
     * @param deleteflag the value for t_board_file_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.deletedate
     *
     * @return the value of t_board_file_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.deletedate
     *
     * @param deletedate the value for t_board_file_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_board_file_info.deleteuser
     *
     * @return the value of t_board_file_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_board_file_info.deleteuser
     *
     * @param deleteuser the value for t_board_file_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}