package jp.co.softwiz.main.domain;

import java.util.Date;

public class TCateMain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.maincode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String maincode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.mainname
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String mainname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.usediv
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String usediv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.etcdesc
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String etcdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.createdate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.createuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.modifydate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.modifyuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String modifyuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.deleteflag
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String deleteflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.deletedate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Date deletedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_main.deleteuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String deleteuser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.maincode
	 * @return  the value of t_cate_main.maincode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getMaincode() {
		return maincode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.maincode
	 * @param maincode  the value for t_cate_main.maincode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setMaincode(String maincode) {
		this.maincode = maincode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.mainname
	 * @return  the value of t_cate_main.mainname
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getMainname() {
		return mainname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.mainname
	 * @param mainname  the value for t_cate_main.mainname
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setMainname(String mainname) {
		this.mainname = mainname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.usediv
	 * @return  the value of t_cate_main.usediv
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getUsediv() {
		return usediv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.usediv
	 * @param usediv  the value for t_cate_main.usediv
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setUsediv(String usediv) {
		this.usediv = usediv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.etcdesc
	 * @return  the value of t_cate_main.etcdesc
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getEtcdesc() {
		return etcdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.etcdesc
	 * @param etcdesc  the value for t_cate_main.etcdesc
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setEtcdesc(String etcdesc) {
		this.etcdesc = etcdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.createdate
	 * @return  the value of t_cate_main.createdate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.createdate
	 * @param createdate  the value for t_cate_main.createdate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.createuser
	 * @return  the value of t_cate_main.createuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.createuser
	 * @param createuser  the value for t_cate_main.createuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.modifydate
	 * @return  the value of t_cate_main.modifydate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.modifydate
	 * @param modifydate  the value for t_cate_main.modifydate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.modifyuser
	 * @return  the value of t_cate_main.modifyuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getModifyuser() {
		return modifyuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.modifyuser
	 * @param modifyuser  the value for t_cate_main.modifyuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setModifyuser(String modifyuser) {
		this.modifyuser = modifyuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.deleteflag
	 * @return  the value of t_cate_main.deleteflag
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getDeleteflag() {
		return deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.deleteflag
	 * @param deleteflag  the value for t_cate_main.deleteflag
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.deletedate
	 * @return  the value of t_cate_main.deletedate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Date getDeletedate() {
		return deletedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.deletedate
	 * @param deletedate  the value for t_cate_main.deletedate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setDeletedate(Date deletedate) {
		this.deletedate = deletedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_main.deleteuser
	 * @return  the value of t_cate_main.deleteuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getDeleteuser() {
		return deleteuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_main.deleteuser
	 * @param deleteuser  the value for t_cate_main.deleteuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setDeleteuser(String deleteuser) {
		this.deleteuser = deleteuser;
	}
}