package jp.co.softwiz.main.domain;

import java.io.Serializable;
import java.util.Date;

public class TCateSub  implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.maincode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String maincode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.subcode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String subcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.subname
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String subname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.subvalue
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String subvalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.subvalue2
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String subvalue2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.subvalue3
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String subvalue3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.vieworder
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Integer vieworder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.usediv
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String usediv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.etcdesc
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String etcdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.createdate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.createuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.modifydate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.modifyuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String modifyuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.deleteflag
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String deleteflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.deletedate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private Date deletedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cate_sub.deleteuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	private String deleteuser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.maincode
	 * @return  the value of t_cate_sub.maincode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getMaincode() {
		return maincode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.maincode
	 * @param maincode  the value for t_cate_sub.maincode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setMaincode(String maincode) {
		this.maincode = maincode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.subcode
	 * @return  the value of t_cate_sub.subcode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getSubcode() {
		return subcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.subcode
	 * @param subcode  the value for t_cate_sub.subcode
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setSubcode(String subcode) {
		this.subcode = subcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.subname
	 * @return  the value of t_cate_sub.subname
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getSubname() {
		return subname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.subname
	 * @param subname  the value for t_cate_sub.subname
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setSubname(String subname) {
		this.subname = subname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.subvalue
	 * @return  the value of t_cate_sub.subvalue
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getSubvalue() {
		return subvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.subvalue
	 * @param subvalue  the value for t_cate_sub.subvalue
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setSubvalue(String subvalue) {
		this.subvalue = subvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.subvalue2
	 * @return  the value of t_cate_sub.subvalue2
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getSubvalue2() {
		return subvalue2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.subvalue2
	 * @param subvalue2  the value for t_cate_sub.subvalue2
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setSubvalue2(String subvalue2) {
		this.subvalue2 = subvalue2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.subvalue3
	 * @return  the value of t_cate_sub.subvalue3
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getSubvalue3() {
		return subvalue3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.subvalue3
	 * @param subvalue3  the value for t_cate_sub.subvalue3
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setSubvalue3(String subvalue3) {
		this.subvalue3 = subvalue3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.vieworder
	 * @return  the value of t_cate_sub.vieworder
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Integer getVieworder() {
		return vieworder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.vieworder
	 * @param vieworder  the value for t_cate_sub.vieworder
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setVieworder(Integer vieworder) {
		this.vieworder = vieworder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.usediv
	 * @return  the value of t_cate_sub.usediv
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getUsediv() {
		return usediv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.usediv
	 * @param usediv  the value for t_cate_sub.usediv
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setUsediv(String usediv) {
		this.usediv = usediv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.etcdesc
	 * @return  the value of t_cate_sub.etcdesc
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getEtcdesc() {
		return etcdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.etcdesc
	 * @param etcdesc  the value for t_cate_sub.etcdesc
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setEtcdesc(String etcdesc) {
		this.etcdesc = etcdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.createdate
	 * @return  the value of t_cate_sub.createdate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.createdate
	 * @param createdate  the value for t_cate_sub.createdate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.createuser
	 * @return  the value of t_cate_sub.createuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.createuser
	 * @param createuser  the value for t_cate_sub.createuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.modifydate
	 * @return  the value of t_cate_sub.modifydate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.modifydate
	 * @param modifydate  the value for t_cate_sub.modifydate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.modifyuser
	 * @return  the value of t_cate_sub.modifyuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getModifyuser() {
		return modifyuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.modifyuser
	 * @param modifyuser  the value for t_cate_sub.modifyuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setModifyuser(String modifyuser) {
		this.modifyuser = modifyuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.deleteflag
	 * @return  the value of t_cate_sub.deleteflag
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getDeleteflag() {
		return deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.deleteflag
	 * @param deleteflag  the value for t_cate_sub.deleteflag
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.deletedate
	 * @return  the value of t_cate_sub.deletedate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public Date getDeletedate() {
		return deletedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.deletedate
	 * @param deletedate  the value for t_cate_sub.deletedate
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setDeletedate(Date deletedate) {
		this.deletedate = deletedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cate_sub.deleteuser
	 * @return  the value of t_cate_sub.deleteuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public String getDeleteuser() {
		return deleteuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cate_sub.deleteuser
	 * @param deleteuser  the value for t_cate_sub.deleteuser
	 * @mbggenerated  Tue Apr 08 10:21:04 JST 2014
	 */
	public void setDeleteuser(String deleteuser) {
		this.deleteuser = deleteuser;
	}
}