package jp.co.softwiz.main.domain;

import java.util.Date;

public class TCompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.companycode
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String companycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.companyname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.realname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.zipcode
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.gender
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.address
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.address2
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.nearstation
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String nearstation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.telnum
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.celphone
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String celphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.mailaddress
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String mailaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.password
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.imageurl
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.etcdesc
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String etcdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.createdate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.createuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.modifydate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.modifyuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.deleteflag
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.deletedate
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_info.deleteuser
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.siteid
     *
     * @return the value of t_company_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.siteid
     *
     * @param siteid the value for t_company_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.companycode
     *
     * @return the value of t_company_info.companycode
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.companycode
     *
     * @param companycode the value for t_company_info.companycode
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.companyname
     *
     * @return the value of t_company_info.companyname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.companyname
     *
     * @param companyname the value for t_company_info.companyname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.realname
     *
     * @return the value of t_company_info.realname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.realname
     *
     * @param realname the value for t_company_info.realname
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.zipcode
     *
     * @return the value of t_company_info.zipcode
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.zipcode
     *
     * @param zipcode the value for t_company_info.zipcode
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.gender
     *
     * @return the value of t_company_info.gender
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.gender
     *
     * @param gender the value for t_company_info.gender
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.address
     *
     * @return the value of t_company_info.address
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.address
     *
     * @param address the value for t_company_info.address
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.address2
     *
     * @return the value of t_company_info.address2
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.address2
     *
     * @param address2 the value for t_company_info.address2
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.nearstation
     *
     * @return the value of t_company_info.nearstation
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getNearstation() {
        return nearstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.nearstation
     *
     * @param nearstation the value for t_company_info.nearstation
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setNearstation(String nearstation) {
        this.nearstation = nearstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.telnum
     *
     * @return the value of t_company_info.telnum
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.telnum
     *
     * @param telnum the value for t_company_info.telnum
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.celphone
     *
     * @return the value of t_company_info.celphone
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getCelphone() {
        return celphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.celphone
     *
     * @param celphone the value for t_company_info.celphone
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCelphone(String celphone) {
        this.celphone = celphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.mailaddress
     *
     * @return the value of t_company_info.mailaddress
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getMailaddress() {
        return mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.mailaddress
     *
     * @param mailaddress the value for t_company_info.mailaddress
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setMailaddress(String mailaddress) {
        this.mailaddress = mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.password
     *
     * @return the value of t_company_info.password
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.password
     *
     * @param password the value for t_company_info.password
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.imageurl
     *
     * @return the value of t_company_info.imageurl
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.imageurl
     *
     * @param imageurl the value for t_company_info.imageurl
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.etcdesc
     *
     * @return the value of t_company_info.etcdesc
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getEtcdesc() {
        return etcdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.etcdesc
     *
     * @param etcdesc the value for t_company_info.etcdesc
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setEtcdesc(String etcdesc) {
        this.etcdesc = etcdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.createdate
     *
     * @return the value of t_company_info.createdate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.createdate
     *
     * @param createdate the value for t_company_info.createdate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.createuser
     *
     * @return the value of t_company_info.createuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.createuser
     *
     * @param createuser the value for t_company_info.createuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.modifydate
     *
     * @return the value of t_company_info.modifydate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.modifydate
     *
     * @param modifydate the value for t_company_info.modifydate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.modifyuser
     *
     * @return the value of t_company_info.modifyuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.modifyuser
     *
     * @param modifyuser the value for t_company_info.modifyuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.deleteflag
     *
     * @return the value of t_company_info.deleteflag
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.deleteflag
     *
     * @param deleteflag the value for t_company_info.deleteflag
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.deletedate
     *
     * @return the value of t_company_info.deletedate
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.deletedate
     *
     * @param deletedate the value for t_company_info.deletedate
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_info.deleteuser
     *
     * @return the value of t_company_info.deleteuser
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_info.deleteuser
     *
     * @param deleteuser the value for t_company_info.deleteuser
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}