package jp.co.softwiz.main.domain;

import java.util.Date;

public class TCompanyPaidServiceHistoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.historyno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Integer historyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.siteid
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.companycode
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String companycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.servicecode
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String servicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String usediv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.startday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String startday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.endday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String endday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.paymentdiv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String paymentdiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.etc
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String etc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.registday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String registday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_paid_service_history_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.historyno
     *
     * @return the value of t_company_paid_service_history_info.historyno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Integer getHistoryno() {
        return historyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.historyno
     *
     * @param historyno the value for t_company_paid_service_history_info.historyno
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setHistoryno(Integer historyno) {
        this.historyno = historyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.siteid
     *
     * @return the value of t_company_paid_service_history_info.siteid
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.siteid
     *
     * @param siteid the value for t_company_paid_service_history_info.siteid
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.companycode
     *
     * @return the value of t_company_paid_service_history_info.companycode
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.companycode
     *
     * @param companycode the value for t_company_paid_service_history_info.companycode
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.servicecode
     *
     * @return the value of t_company_paid_service_history_info.servicecode
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getServicecode() {
        return servicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.servicecode
     *
     * @param servicecode the value for t_company_paid_service_history_info.servicecode
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setServicecode(String servicecode) {
        this.servicecode = servicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.usediv
     *
     * @return the value of t_company_paid_service_history_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getUsediv() {
        return usediv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.usediv
     *
     * @param usediv the value for t_company_paid_service_history_info.usediv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setUsediv(String usediv) {
        this.usediv = usediv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.startday
     *
     * @return the value of t_company_paid_service_history_info.startday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getStartday() {
        return startday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.startday
     *
     * @param startday the value for t_company_paid_service_history_info.startday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setStartday(String startday) {
        this.startday = startday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.endday
     *
     * @return the value of t_company_paid_service_history_info.endday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getEndday() {
        return endday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.endday
     *
     * @param endday the value for t_company_paid_service_history_info.endday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setEndday(String endday) {
        this.endday = endday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.paymentdiv
     *
     * @return the value of t_company_paid_service_history_info.paymentdiv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getPaymentdiv() {
        return paymentdiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.paymentdiv
     *
     * @param paymentdiv the value for t_company_paid_service_history_info.paymentdiv
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setPaymentdiv(String paymentdiv) {
        this.paymentdiv = paymentdiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.etc
     *
     * @return the value of t_company_paid_service_history_info.etc
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getEtc() {
        return etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.etc
     *
     * @param etc the value for t_company_paid_service_history_info.etc
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setEtc(String etc) {
        this.etc = etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.registday
     *
     * @return the value of t_company_paid_service_history_info.registday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getRegistday() {
        return registday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.registday
     *
     * @param registday the value for t_company_paid_service_history_info.registday
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setRegistday(String registday) {
        this.registday = registday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.createdate
     *
     * @return the value of t_company_paid_service_history_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.createdate
     *
     * @param createdate the value for t_company_paid_service_history_info.createdate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.createuser
     *
     * @return the value of t_company_paid_service_history_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.createuser
     *
     * @param createuser the value for t_company_paid_service_history_info.createuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.modifydate
     *
     * @return the value of t_company_paid_service_history_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.modifydate
     *
     * @param modifydate the value for t_company_paid_service_history_info.modifydate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.modifyuser
     *
     * @return the value of t_company_paid_service_history_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.modifyuser
     *
     * @param modifyuser the value for t_company_paid_service_history_info.modifyuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.deleteflag
     *
     * @return the value of t_company_paid_service_history_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.deleteflag
     *
     * @param deleteflag the value for t_company_paid_service_history_info.deleteflag
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.deletedate
     *
     * @return the value of t_company_paid_service_history_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.deletedate
     *
     * @param deletedate the value for t_company_paid_service_history_info.deletedate
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_paid_service_history_info.deleteuser
     *
     * @return the value of t_company_paid_service_history_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_paid_service_history_info.deleteuser
     *
     * @param deleteuser the value for t_company_paid_service_history_info.deleteuser
     *
     * @mbggenerated Fri Apr 25 10:48:29 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}