package jp.co.softwiz.main.domain;

import java.util.Date;

public class TNewsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.newsno
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private Integer newsno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.title
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.content
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.yyyymmdd
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String yyyymmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.createdate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.createuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.modifydate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.modifyuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.deleteflag
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.deletedate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.deleteuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.newsno
     *
     * @return the value of t_news_info.newsno
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public Integer getNewsno() {
        return newsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.newsno
     *
     * @param newsno the value for t_news_info.newsno
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setNewsno(Integer newsno) {
        this.newsno = newsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.siteid
     *
     * @return the value of t_news_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.siteid
     *
     * @param siteid the value for t_news_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.title
     *
     * @return the value of t_news_info.title
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.title
     *
     * @param title the value for t_news_info.title
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.content
     *
     * @return the value of t_news_info.content
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.content
     *
     * @param content the value for t_news_info.content
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.yyyymmdd
     *
     * @return the value of t_news_info.yyyymmdd
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getYyyymmdd() {
        return yyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.yyyymmdd
     *
     * @param yyyymmdd the value for t_news_info.yyyymmdd
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setYyyymmdd(String yyyymmdd) {
        this.yyyymmdd = yyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.createdate
     *
     * @return the value of t_news_info.createdate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.createdate
     *
     * @param createdate the value for t_news_info.createdate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.createuser
     *
     * @return the value of t_news_info.createuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.createuser
     *
     * @param createuser the value for t_news_info.createuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.modifydate
     *
     * @return the value of t_news_info.modifydate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.modifydate
     *
     * @param modifydate the value for t_news_info.modifydate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.modifyuser
     *
     * @return the value of t_news_info.modifyuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.modifyuser
     *
     * @param modifyuser the value for t_news_info.modifyuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.deleteflag
     *
     * @return the value of t_news_info.deleteflag
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.deleteflag
     *
     * @param deleteflag the value for t_news_info.deleteflag
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.deletedate
     *
     * @return the value of t_news_info.deletedate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.deletedate
     *
     * @param deletedate the value for t_news_info.deletedate
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.deleteuser
     *
     * @return the value of t_news_info.deleteuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.deleteuser
     *
     * @param deleteuser the value for t_news_info.deleteuser
     *
     * @mbggenerated Mon Apr 21 09:56:05 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}