package jp.co.softwiz.main.domain;

import java.util.Date;

public class TQnaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.qnano
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private Integer qnano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.siteid
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.title
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.content
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.yyyymmdd
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String yyyymmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.createdate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.createuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.modifydate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.modifyuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.deleteflag
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.deletedate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qna_info.deleteuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.qnano
     *
     * @return the value of t_qna_info.qnano
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public Integer getQnano() {
        return qnano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.qnano
     *
     * @param qnano the value for t_qna_info.qnano
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setQnano(Integer qnano) {
        this.qnano = qnano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.siteid
     *
     * @return the value of t_qna_info.siteid
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.siteid
     *
     * @param siteid the value for t_qna_info.siteid
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.title
     *
     * @return the value of t_qna_info.title
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.title
     *
     * @param title the value for t_qna_info.title
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.content
     *
     * @return the value of t_qna_info.content
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.content
     *
     * @param content the value for t_qna_info.content
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.yyyymmdd
     *
     * @return the value of t_qna_info.yyyymmdd
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getYyyymmdd() {
        return yyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.yyyymmdd
     *
     * @param yyyymmdd the value for t_qna_info.yyyymmdd
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setYyyymmdd(String yyyymmdd) {
        this.yyyymmdd = yyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.createdate
     *
     * @return the value of t_qna_info.createdate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.createdate
     *
     * @param createdate the value for t_qna_info.createdate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.createuser
     *
     * @return the value of t_qna_info.createuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.createuser
     *
     * @param createuser the value for t_qna_info.createuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.modifydate
     *
     * @return the value of t_qna_info.modifydate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.modifydate
     *
     * @param modifydate the value for t_qna_info.modifydate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.modifyuser
     *
     * @return the value of t_qna_info.modifyuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.modifyuser
     *
     * @param modifyuser the value for t_qna_info.modifyuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.deleteflag
     *
     * @return the value of t_qna_info.deleteflag
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.deleteflag
     *
     * @param deleteflag the value for t_qna_info.deleteflag
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.deletedate
     *
     * @return the value of t_qna_info.deletedate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.deletedate
     *
     * @param deletedate the value for t_qna_info.deletedate
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qna_info.deleteuser
     *
     * @return the value of t_qna_info.deleteuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qna_info.deleteuser
     *
     * @param deleteuser the value for t_qna_info.deleteuser
     *
     * @mbggenerated Sat May 10 16:50:47 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}