package jp.co.softwiz.main.domain;

public class TSiteInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_info.sitename
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    private String sitename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_info.siteid
     *
     * @return the value of t_site_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_info.siteid
     *
     * @param siteid the value for t_site_info.siteid
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_info.sitename
     *
     * @return the value of t_site_info.sitename
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_info.sitename
     *
     * @param sitename the value for t_site_info.sitename
     *
     * @mbggenerated Mon Apr 21 09:56:06 JST 2014
     */
    public void setSitename(String sitename) {
        this.sitename = sitename;
    }
}