package jp.co.softwiz.main.domain;

import java.util.Date;

public class TTestInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.testno
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String testno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.testname
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String testname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.yearmonthday
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String yearmonthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.detailcontent
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String detailcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.imagepath
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String imagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.filepath
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.createdate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.createuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.modifydate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.modifyuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String modifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.deleteflag
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.deletedate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_info.deleteuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    private String deleteuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.testno
     *
     * @return the value of t_test_info.testno
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getTestno() {
        return testno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.testno
     *
     * @param testno the value for t_test_info.testno
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setTestno(String testno) {
        this.testno = testno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.testname
     *
     * @return the value of t_test_info.testname
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getTestname() {
        return testname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.testname
     *
     * @param testname the value for t_test_info.testname
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setTestname(String testname) {
        this.testname = testname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.yearmonthday
     *
     * @return the value of t_test_info.yearmonthday
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getYearmonthday() {
        return yearmonthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.yearmonthday
     *
     * @param yearmonthday the value for t_test_info.yearmonthday
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setYearmonthday(String yearmonthday) {
        this.yearmonthday = yearmonthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.detailcontent
     *
     * @return the value of t_test_info.detailcontent
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getDetailcontent() {
        return detailcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.detailcontent
     *
     * @param detailcontent the value for t_test_info.detailcontent
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setDetailcontent(String detailcontent) {
        this.detailcontent = detailcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.imagepath
     *
     * @return the value of t_test_info.imagepath
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.imagepath
     *
     * @param imagepath the value for t_test_info.imagepath
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.filepath
     *
     * @return the value of t_test_info.filepath
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.filepath
     *
     * @param filepath the value for t_test_info.filepath
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.createdate
     *
     * @return the value of t_test_info.createdate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.createdate
     *
     * @param createdate the value for t_test_info.createdate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.createuser
     *
     * @return the value of t_test_info.createuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.createuser
     *
     * @param createuser the value for t_test_info.createuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.modifydate
     *
     * @return the value of t_test_info.modifydate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.modifydate
     *
     * @param modifydate the value for t_test_info.modifydate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.modifyuser
     *
     * @return the value of t_test_info.modifyuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.modifyuser
     *
     * @param modifyuser the value for t_test_info.modifyuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.deleteflag
     *
     * @return the value of t_test_info.deleteflag
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.deleteflag
     *
     * @param deleteflag the value for t_test_info.deleteflag
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.deletedate
     *
     * @return the value of t_test_info.deletedate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.deletedate
     *
     * @param deletedate the value for t_test_info.deletedate
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_info.deleteuser
     *
     * @return the value of t_test_info.deleteuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public String getDeleteuser() {
        return deleteuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_info.deleteuser
     *
     * @param deleteuser the value for t_test_info.deleteuser
     *
     * @mbggenerated Fri Apr 11 16:20:56 JST 2014
     */
    public void setDeleteuser(String deleteuser) {
        this.deleteuser = deleteuser;
    }
}